/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cylin' at '9/23/16 6:23 PM' with Gradle 3.0-milestone-1
 *
 * @author cylin, @date 9/23/16 6:23 PM
 */
public class Main {
    public boolean someLibraryMethod() {
        return true;
    }
}
